# Generated by Django 4.2.25 on 2025-10-21 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_checked_in_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('unused', 'Girmedi'), ('used', 'Girdi')], default='unused', max_length=10),
        ),
    ]
